"""Isolated labeled fault operators for the synthetic validation lab.

Faults operate on a validation-case copy.  They never patch or mutate the
canonical pricing implementations.  Model-form operators F01/F02 are marked
as deterministic *proxies* unless the supplied case was generated by a
qualified Bates or LocalVol engine.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Literal

import numpy as np

from derivguard.synthetic.generation import FloatArray
from derivguard.synthetic.observation import ObservedSurface

FaultId = Literal[
    "F00",
    "F01",
    "F02",
    "F03",
    "F04",
    "F05",
    "F06",
    "F07",
    "F08",
    "F09",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
]

FAULT_DESCRIPTIONS: dict[FaultId, str] = {
    "F00": "no fault",
    "F01": "Heston-on-Bates model-form proxy",
    "F02": "Heston-on-LocalVol model-form proxy",
    "F03": "regime shift",
    "F04": "poor integration resolution",
    "F05": "coarse PDE",
    "F06": "insufficient Monte Carlo",
    "F07": "calibration local minimum",
    "F08": "sparse calibration surface",
    "F09": "corrupt quotes",
    "F10": "stale/asynchronous-like observations",
    "F11": "incorrect rate or forward",
    "F12": "wing extrapolation",
    "F13": "maturity extrapolation",
    "F14": "unstable parameters",
    "F15": "biased/inconsistent Greeks",
    "F16": "combined faults",
}


@dataclass(frozen=True)
class ValidationCase:
    surface: ObservedSurface
    fault_id: FaultId
    developer_price: FloatArray
    developer_delta: FloatArray
    developer_gamma: FloatArray
    developer_vega: FloatArray
    numerical_prices: FloatArray  # [observation, independent engine]
    calibration_prices: FloatArray  # [observation, bootstrap draw]
    challenger_prices: FloatArray  # [observation, independent challenger]
    challenger_delta: FloatArray
    challenger_gamma: FloatArray
    challenger_vega: FloatArray
    support_distance: FloatArray
    parameter_drift: FloatArray
    identifiability_score: float
    prior_outcome_score: float
    data_quality_score: float
    regime: str
    materiality_scale: FloatArray
    proxy_fault: bool = False

    @property
    def true_error(self) -> FloatArray:
        return np.abs(self.developer_price - self.surface.truth.true_price)

    @property
    def normalized_true_error(self) -> FloatArray:
        return self.true_error / np.maximum(self.materiality_scale, 1.0e-12)


def clean_validation_case(surface: ObservedSurface, *, bootstrap_draws: int = 8) -> ValidationCase:
    if bootstrap_draws < 2:
        raise ValueError("at least two bootstrap draws are required")
    truth = surface.truth
    price = truth.true_price.copy()
    numerical = np.column_stack((price, price))
    calibration = np.repeat(price[:, None], bootstrap_draws, axis=1)
    challengers = np.column_stack((price, price))
    scale = np.maximum(surface.spread, 0.01)
    median_maturity = float(np.median(truth.design.maturity))
    median_abs_moneyness = float(np.median(np.abs(np.log(truth.design.strike / truth.design.spot))))
    observed_mask = surface.observed & np.isfinite(surface.mid)
    observed_mid = surface.mid[observed_mask]
    observed_spread = surface.spread[observed_mask]
    relative_spread = (
        float(np.median(observed_spread / np.maximum(np.abs(observed_mid), 0.25)))
        if observed_mid.size
        else float("inf")
    )
    regime = "|".join(
        (
            "SHORT" if median_maturity < 0.9 else "LONG",
            "WING" if median_abs_moneyness > 0.18 else "MID",
            "WIDE" if relative_spread > 0.06 else "LIQUID",
        )
    )
    return ValidationCase(
        surface=surface,
        fault_id="F00",
        developer_price=price,
        developer_delta=truth.true_delta.copy(),
        developer_gamma=truth.true_gamma.copy(),
        developer_vega=truth.true_vega.copy(),
        numerical_prices=numerical,
        calibration_prices=calibration,
        challenger_prices=challengers,
        challenger_delta=np.column_stack((truth.true_delta, truth.true_delta)),
        challenger_gamma=np.column_stack((truth.true_gamma, truth.true_gamma)),
        challenger_vega=np.column_stack((truth.true_vega, truth.true_vega)),
        support_distance=np.zeros(len(truth)),
        parameter_drift=np.zeros(5),
        identifiability_score=0.0,
        prior_outcome_score=0.0,
        data_quality_score=float(np.mean(~surface.observed)),
        regime=regime,
        materiality_scale=scale,
    )


def _pattern(case: ValidationCase) -> tuple[FloatArray, FloatArray, FloatArray]:
    design = case.surface.truth.design
    signed_moneyness = np.log(design.strike / design.spot)
    wing = np.clip(np.abs(signed_moneyness) / 0.35, 0.0, 1.0)
    tenor = np.clip(design.maturity / 2.0, 0.0, 1.0)
    scale = np.maximum(case.materiality_scale, 0.01)
    return signed_moneyness, wing, tenor * scale


def inject_fault(
    case: ValidationCase, fault_id: FaultId, *, severity: float = 2.0
) -> ValidationCase:
    """Return an isolated fault case; ``case`` and canonical engines are untouched."""

    if fault_id not in FAULT_DESCRIPTIONS:
        raise ValueError(f"unknown fault id: {fault_id}")
    if severity < 0.0 or not np.isfinite(severity):
        raise ValueError("severity must be finite and non-negative")
    if fault_id == "F00":
        return replace(case, fault_id="F00")
    signed, wing, tenor_scale = _pattern(case)
    scale = np.maximum(case.materiality_scale, 0.01)
    dev = case.developer_price.copy()
    numerical = case.numerical_prices.copy()
    calibration = case.calibration_prices.copy()
    challengers = case.challenger_prices.copy()
    delta = case.developer_delta.copy()
    gamma = case.developer_gamma.copy()
    vega = case.developer_vega.copy()
    support = case.support_distance.copy()
    drift = case.parameter_drift.copy()
    ident = case.identifiability_score
    outcome = case.prior_outcome_score
    data_quality = case.data_quality_score
    regime = case.regime
    proxy = False

    if fault_id == "F01":
        dev += severity * scale * (0.30 + wing) * np.sign(signed + 1.0e-9)
        challengers[:, 0] -= severity * scale * (0.25 + wing)
        proxy = case.surface.truth.model_id != "SYN-BATES"
    elif fault_id == "F02":
        dev += severity * scale * np.sin(8.0 * signed) * (0.25 + wing)
        challengers[:, 1] -= severity * scale * np.sin(8.0 * signed)
        proxy = case.surface.truth.model_id != "SYN-LOCALVOL"
    elif fault_id == "F03":
        dev += severity * scale * (0.5 + tenor_scale / scale)
        drift += severity
    elif fault_id == "F04":
        numerical[:, 0] += severity * scale * (0.2 + wing)
        dev += 0.5 * severity * scale * (0.2 + wing)
    elif fault_id == "F05":
        numerical[:, 1] -= severity * scale * (0.2 + tenor_scale / scale)
    elif fault_id == "F06":
        alternating = np.where(np.arange(dev.size) % 2 == 0, 1.0, -1.0)
        numerical[:, 0] += severity * scale * alternating
    elif fault_id == "F07":
        dev += severity * scale * (0.5 + wing)
        calibration += np.linspace(-1.0, 1.0, calibration.shape[1]) * severity * scale[:, None]
    elif fault_id == "F08":
        support += severity * (0.5 + wing)
        calibration += np.linspace(-0.5, 0.5, calibration.shape[1]) * severity * scale[:, None]
    elif fault_id == "F09":
        # Quote corruption is represented in E_data without modifying immutable observations.
        data_quality += severity
    elif fault_id == "F10":
        support += severity * (0.25 + wing)
        data_quality += 0.5 * severity
    elif fault_id == "F11":
        dev += (
            severity * 0.02 * case.surface.truth.design.strike * case.surface.truth.design.maturity
        )
    elif fault_id == "F12":
        dev += severity * scale * wing
        support += severity * wing
    elif fault_id == "F13":
        long_tenor = np.clip((case.surface.truth.design.maturity - 0.5) / 1.5, 0.0, 1.0)
        dev += severity * scale * long_tenor
        support += severity * long_tenor
    elif fault_id == "F14":
        drift += severity * np.asarray([1.0, -0.7, 0.8, 1.2, -0.9])
        ident += severity
    elif fault_id == "F15":
        delta += 0.05 * severity
        gamma *= 1.0 + 0.30 * severity
        vega *= 1.0 - 0.20 * severity
    elif fault_id == "F16":
        combined = inject_fault(case, "F04", severity=severity)
        combined = inject_fault(combined, "F09", severity=severity)
        combined = inject_fault(combined, "F14", severity=severity)
        return replace(combined, fault_id="F16")
    return replace(
        case,
        fault_id=fault_id,
        developer_price=dev,
        developer_delta=delta,
        developer_gamma=gamma,
        developer_vega=vega,
        numerical_prices=numerical,
        calibration_prices=calibration,
        challenger_prices=challengers,
        support_distance=support,
        parameter_drift=drift,
        identifiability_score=ident,
        prior_outcome_score=outcome,
        data_quality_score=data_quality,
        regime=regime,
        proxy_fault=proxy,
    )
